### ISSUE TITLE
Need to update docs and correct slip in code

### ISSUE THREAD

**Issue by degibons** [abouolia/sticky-sidebar#1]
Thanks for great plugin, but seems the documentation is out of date. Also you have a slip in code (section "Plugin Definition"):
```javascript
if (data[config] === undefined && ['destory', 'updateSticky'].indexOf(config) != -1) {
                    throw new Error('No method named "'+ config +'"');
                }
```
You have 'destory', but must be 'destroy'.

**Comment by abouolia** [comment]
I'm sorry, i wrote the documentation in fast, anyway I've fixed all slips in code and updated the documentation, if there's any issue please don't hesitate to write about it and i'll fix it as soon as possible. Thanks.

**Comment by degibons** [comment]
I think I've found more. This one:
```javascript
.on('resize.'+ StickySidebar.EVENT_KEY, $.proxy(this._onResize, this))
.on('scroll.'+ StickySidebar.EVENT_KEY, $.proxy(this._onScroll, this));
.on('update.' + StickySidebar.EVENT_KEY, $.proxy(this.updateSticky, this));
```
and:
```javascript
 .off('recalcDimenstions' + StickySidebar.EVENT_KEY)
```

Also, what do tou think if "innerWrapperClass" turn to "innerWrapperSelector", just for consistency reason?

**Comment by abouolia** [comment]
I've fixed it, thanks for cooperation, About replacing `innerWrapperClass` to `innerWrapperSelector` i thought twice to do that, but it didn't work because `innerWrapperClass` will use as selector if found it a one or wrapper will be created and add on it the same class name, you can't do that with `innerWrapperSelector`, or to avoid adding class on wrapper of sticky sidebar or will be separated in each option, you can give me some suggestions or even pull request.

**Comment by degibons** [comment]
I've created a pull request about innerWrapSelector issue. You decide merge it or not, but I think if the user don't provided InnerWrapper there is no reason to set specific class to generated wrap.

Another thing, I've noticed in your docs is about css:
```css
.sidebar__inner{
    transform: translate3d(0, 0, 0);
    transform: translate(0, 0); /* For browsers don't support translate3d. */
    will-change: position, transform;
}
```
maybe more correct will be to change order of transform option:
```css
.sidebar__inner{
    transform: translate(0, 0); /* For browsers don't support translate3d. */
    transform: translate3d(0, 0, 0);
    will-change: position, transform;
}
```

What do you think?
